/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

#include "PluginBase.h"
#include "CPedAcquaintance.h"

enum PLUGIN_API ePedStats {
	PEDSTAT_PLAYER = 0,
	PEDSTAT_COP = 1,
	PEDSTAT_MEDIC = 2,
	PEDSTAT_FIRE = 3,
	PEDSTAT_GANG1 = 4,
	PEDSTAT_GANG2 = 5,
	PEDSTAT_GANG3 = 6,
	PEDSTAT_GANG4 = 7,
	PEDSTAT_GANG5 = 8,
	PEDSTAT_GANG6 = 9,
	PEDSTAT_GANG7 = 10,
	PEDSTAT_GANG8 = 11,
	PEDSTAT_GANG9 = 12,
	PEDSTAT_GANG10 = 13,
	PEDSTAT_STREET_GUY = 14,
	PEDSTAT_SUIT_GUY = 15,
	PEDSTAT_SENSIBLE_GUY = 16,
	PEDSTAT_GEEK_GUY = 17,
	PEDSTAT_OLD_GUY = 18,
	PEDSTAT_TOUGH_GUY = 19,
	PEDSTAT_STREET_GIRL = 20,
	PEDSTAT_SUIT_GIRL = 21,
	PEDSTAT_SENSIBLE_GIRL = 22,
	PEDSTAT_GEEK_GIRL = 23,
	PEDSTAT_OLD_GIRL = 24,
	PEDSTAT_TOUGH_GIRL = 25,
	PEDSTAT_TRAMP_MALE = 26,
	PEDSTAT_TRAMP_FEMALE = 27,
	PEDSTAT_TOURIST = 28,
	PEDSTAT_PROSTITUTE = 29,
	PEDSTAT_CRIMINAL = 30,
	PEDSTAT_BUSKER = 31,
	PEDSTAT_TAXIDRIVER = 32,
	PEDSTAT_PSYCHO = 33,
	PEDSTAT_STEWARD = 34,
	PEDSTAT_SPORTSFAN = 35,
	PEDSTAT_SHOPPER = 36,
	PEDSTAT_OLDSHOPPER = 37,
	PEDSTAT_BEACH_GUY = 38,
	PEDSTAT_BEACH_GIRL = 39,
	PEDSTAT_SKATER = 40,
	PEDSTAT_STD_MISSION = 41,
	PEDSTAT_COWARD = 42,
	PEDSTAT_NUM
};

class CPedType {
public:
    static CPedAcquaintance*& ms_apPedTypes;

    static void Load();
    static void Save();
};

