/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eCrimeType {
    CRIME_NONE = 0,
	CRIME_POSSESSION_GUN,
	CRIME_HIT_PED,
	CRIME_HIT_COP,
	CRIME_SHOOT_PED,
	CRIME_SHOOT_COP,
	CRIME_STEAL_CAR,
	CRIME_RUN_REDLIGHT,
	CRIME_RECKLESS_DRIVING,
	CRIME_SPEEDING,
	CRIME_RUNOVER_PED,
	CRIME_RUNOVER_COP,
	CRIME_DESTROY_HELI,
	CRIME_PED_SET_ON_FIRE,
	CRIME_COP_SET_ON_FIRE,
	CRIME_CAR_SET_ON_FIRE,
	CRIME_DESTROY_PLANE,
	CRIME_CAUSE_EXPLOSION,
	CRIME_STAB_PED,
	CRIME_STAB_COP,
	CRIME_DESTROY_VEHICLE,
	CRIME_DAMAGE_TO_PROPERTY,
	CRIME_TARGET_COP,
	MAX_CRIMES
};