/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum ePedBones
{
	BONE_PELVIS1 = 1,
	BONE_PELVIS = 2,
	BONE_SPINE1 = 3,
	BONE_UPPERTORSO = 4,
	BONE_NECK = 5,
	BONE_HEAD2 = 6,
	BONE_HEAD1 = 7,
	BONE_HEAD = 8,
	BONE_RIGHTUPPERTORSO = 21,
	BONE_RIGHTSHOULDER = 22,
	BONE_RIGHTELBOW = 23,
	BONE_RIGHTWRIST = 24,
	BONE_RIGHTHAND = 25,
	BONE_RIGHTTHUMB = 26,
	BONE_LEFTUPPERTORSO = 31,
	BONE_LEFTSHOULDER = 32,
	BONE_LEFTELBOW = 33,
	BONE_LEFTWRIST = 34,
	BONE_LEFTHAND = 35,
	BONE_LEFTTHUMB = 36,
	BONE_LEFTHIP = 41,
	BONE_LEFTKNEE = 42,
	BONE_LEFTANKLE = 43,
	BONE_LEFTFOOT = 44,
	BONE_RIGHTHIP = 51,
	BONE_RIGHTKNEE = 52,
	BONE_RIGHTANKLE = 53,
	BONE_RIGHTFOOT = 54,
};

enum
{
	BONETAG_ROOT = 0,
	BONETAG_PELVIS,
	BONETAG_SPINE,
	BONETAG_SPINE1,
	BONETAG_NECK,
	BONETAG_HEAD,
	BONETAG_L_BROW,
	BONETAG_R_BROW,
	BONETAG_JAW,
	BONETAG_R_CLAVICLE = 21,
	BONETAG_R_UPPERARM,
	BONETAG_R_FOREARM,
	BONETAG_R_HAND,
	BONETAG_R_FINGERS,
	BONETAG_R_FINGER01,
	BONETAG_L_CLAVICLE = 31,
	BONETAG_L_UPPERARM,
	BONETAG_L_FOREARM,
	BONETAG_L_HAND,
	BONETAG_L_FINGERS,
	BONETAG_L_FINGER01,
	BONETAG_L_THIGH = 41,
	BONETAG_L_CALF,
	BONETAG_L_FOOT,
	BONETAG_L_TOE,
	BONETAG_R_THIGH = 51,
	BONETAG_R_CALF,
	BONETAG_R_FOOT,
	BONETAG_R_TOE,
	BONETAG_BELLY = 201,
	BONETAG_R_BREAST = 301,
	BONETAG_L_BREAST
};

